# Project setup:
Rails:
  Enabled: true
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

# Cop configuration:

# Bundler

# Gemspec

# Layout
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/AlignHash:
  Enabled: false
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false

# Lint
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
Lint/HandleExceptions:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Naming
Naming/PredicateName:
  Enabled: false

# Performance

# Rails
Rails/FilePath:
  Enabled: false

# Security

# Style
Style/BlockDelimiters:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
# It would be nice to have this on, but I'm not up for writing 66 of these in
# the process of addressing the initial 4,489 cop warnings.
Style/Documentation:
  Enabled: false
  Exclude: [db/migrate/**/*, spec/**/*, test/**/*]
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Style/IfUnlessModifier:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/NegatedIf:
  EnforcedStyle: postfix
Style/NumericPredicate:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
