# Project setup:
Rails:
  Enabled: true
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

# Cop configuration:

# Bundler

# Gemspec

# Layout
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

# Lint

# Metrics

# Naming

# Performance

# Rails

# Security

# Style
Style/RedundantReturn:
  Enabled: false
Style/StringLiterals:
  Enabled: false
